<?php declare(strict_types=1);

use SanderMuller\BoostCore\Config\BoostConfig;
use SanderMuller\BoostCore\Enums\Agent;
use SanderMuller\BoostCore\Enums\Tag;
use SanderMuller\ProjectBoostLaravel\Rendering\BladeRenderer;

/**
 * boost-core configuration.
 *
 * Generated by `vendor/bin/boost install`. Re-run that command to update
 * agents/vendors interactively, or hand-edit this file. After changes
 * run `vendor/bin/boost sync`.
 *
 * Docs: https://github.com/sandermuller/boost-core
 */
return BoostConfig::configure()
    // Which AI agents to publish skills/guidelines to. Add Agent enum cases.
    // Example: Agent::CLAUDE_CODE, Agent::CURSOR, Agent::COPILOT
    ->withAgents([
        Agent::CLAUDE_CODE,
        Agent::CODEX,
        Agent::COPILOT,
    ])

    // Vendor packages allowed to publish skills/guidelines into your project.
    // Each entry is a Composer package name. Add via `vendor/bin/boost scan` or hand-edit.
    ->withAllowedVendors([
        'barryvdh/laravel-debugbar',
        'laravel/boost',
        'laravel/mcp',
        'laravel/passport',
        'laravel/socialite',
        'sandermuller/boost-skills',
        'sandermuller/laravel-fluent-validation',
        'sandermuller/laravel-fluent-validation-rector',
        'sandermuller/richter',
        'sandermuller/stopwatch',
        'laravel/fortify',
        'filament/filament',
    ])

    // Optionally disable specific FileEmitter implementations by FQCN.
    // ->withDisabledEmitters([SomeFqcn::class])

    // Skill tags: a vendor skill ships only when every tag in its
    // `metadata.boost-tags` is declared here. Unset = receive every
    // (untagged) skill. Accepts Tag enum cases or raw strings.
    ->withTags([
        Tag::Php,
        Tag::Laravel,
        Tag::Frontend,
        Tag::Database,
        Tag::Livewire,
        Tag::Filament,
        Tag::Tailwind,
        Tag::Github,
        'release-automation',
        'voice',
        'laravel-cloud',
        'hosting',
    ])

    // Project Conventions: fills the slot vocabulary that sandermuller/boost-skills
    // vendor skills reference. Validated by `vendor/bin/boost validate`.
    ->withConventions([
        'schema-version' => 1,
        'github' => [
            'owner' => 'SanderMuller',
            'repo' => 'dipcatch',
            'default_base_branch' => 'main',
        ],
        'testing' => [
            'backend_framework' => 'pest',
        ],
        'quality' => [
            'rector' => true,
            // This project declares three pipelines, so evaluate has to be told
            // which one to ask about; without a name it gets an error listing
            // them and runs every check itself. `closeout` rather than `change`
            // because evaluate is a completion-level activity — it runs before
            // review, and only that walk covers Rector and the whole PHP suite.
            'pipeline' => 'closeout',
        ],
    ])

    // Composer-package authoring skills — not relevant to this application.
    // Pulled in by the release-automation tag alongside the wanted pre-release skill.
    //
    // The laravel/boost entries are frameworks this app does not use. Its
    // catalogue arrives through sandermuller/project-boost-laravel, which
    // ships everything Boost detects, so the unused stacks are dropped here.
    ->withExcludedSkills([
        'laravel/boost:inertia-react-development',
        'laravel/boost:inertia-svelte-development',
        'laravel/boost:inertia-vue-development',
        'laravel/boost:wayfinder-development',
        'sandermuller/boost-skills:readme',
        'sandermuller/boost-skills:pre-release',
        'sandermuller/boost-skills:release-notes',
        'sandermuller/boost-skills:upgrading',
        // Subagents share the skill deny-list. This project authors its own
        // DipCatch-specific tech-lead-reviewer and test-coverage-auditor in
        // `.ai/subagents/`; without these two entries both names are declared
        // twice and Claude Code picks one by filesystem read order.
        'sandermuller/boost-skills:tech-lead-reviewer',
        'sandermuller/boost-skills:test-coverage-auditor',
    ])

    ->withExcludedGuidelines([
        'laravel/boost:inertia-laravel-core',
        'laravel/boost:inertia-react-core',
        'laravel/boost:inertia-svelte-core',
        'laravel/boost:inertia-vue-core',
        'laravel/boost:phpunit-core',
        'laravel/boost:sail-core',
        'laravel/boost:wayfinder-core',
    ])

    // Without a renderer, the `.blade.php` vendor skills of laravel/mcp,
    // laravel/passport and laravel/socialite are skipped silently.
    ->withSkillRenderers([new BladeRenderer()]);
