<?php declare(strict_types=1);

use SanderMuller\BoostCore\Config\BoostConfig;
use SanderMuller\BoostCore\Enums\Agent;
use SanderMuller\BoostCore\Enums\Tag;

/**
 * boost-core configuration.
 *
 * Generated by `vendor/bin/boost install`. Re-run that command to update
 * agents/vendors interactively, or hand-edit this file. After changes
 * run `vendor/bin/boost sync`.
 *
 * Docs: https://github.com/sandermuller/boost-core
 */
return BoostConfig::configure()
    // Which AI agents to publish skills/guidelines to. Add Agent enum cases.
    // Example: Agent::CLAUDE_CODE, Agent::CURSOR, Agent::COPILOT
    ->withAgents([
        Agent::CLAUDE_CODE,
        Agent::COPILOT,
    ])

    // Vendor packages allowed to publish skills/guidelines into your project.
    // Each entry is a Composer package name. Add via `vendor/bin/boost scan` or hand-edit.
    ->withAllowedVendors([
        'sandermuller/boost-skills',
        'sandermuller/laravel-fluent-validation',
        'sandermuller/laravel-fluent-validation-rector',
        'sandermuller/richter',
        'sandermuller/stopwatch',
        'laravel/fortify',
        'filament/filament',
    ])

    // Optionally disable specific FileEmitter implementations by FQCN.
    // ->withDisabledEmitters([SomeFqcn::class])

    // Skill tags: a vendor skill ships only when every tag in its
    // `metadata.boost-tags` is declared here. Unset = receive every
    // (untagged) skill. Accepts Tag enum cases or raw strings.
    ->withTags([
        Tag::Php,
        Tag::Laravel,
        Tag::Frontend,
        Tag::Database,
        Tag::Github,
        'release-automation',
        'voice',
    ])

    // Project Conventions: fills the slot vocabulary that sandermuller/boost-skills
    // vendor skills reference. Validated by `vendor/bin/boost validate`.
    ->withConventions([
        'schema-version' => 1,
        'github' => [
            'owner' => 'SanderMuller',
            'repo' => 'dipcatch',
            'default_base_branch' => 'main',
        ],
        'testing' => [
            'backend_framework' => 'pest',
        ],
        'quality' => [
            'rector' => true,
        ],
    ])

    // Composer-package authoring skills — not relevant to this application.
    // Pulled in by the release-automation tag alongside the wanted pre-release skill.
    ->withExcludedSkills([
        'sandermuller/boost-skills:readme',
        'sandermuller/boost-skills:pre-release',
        'sandermuller/boost-skills:release-notes',
        'sandermuller/boost-skills:upgrading',
    ]);
